### ISSUE TITLE
请问SDN是否是该系统的更优解

### ISSUE THREAD

**Issue by kwingen** [AlbumenJ/switch-monitor#1]
我是网络工程专业的学生，两年前看到项目的php版本。当时就感觉要适配不同交换机的命令工程量未免太大，于是和老师说我自己无法完成。后来又深入了解了SDN，感觉SDN会是更优解，但才疏学浅，不敢下定论，所以来请教一下

**Comment by chn-lee-yumi** [comment]
这个项目没有PHP版本……

**Comment by kwingen** [comment]
https://github.com/picone/SwitchManage/blob/master/README.md
不是同一个项目吗？
@chn-lee-yumi

**Comment by chn-lee-yumi** [comment]
@kwingen 不是
